version: '3.7'

services:
  baget-postgres:
    image: postgres:16
    container_name: baget-postgres
    environment:
      POSTGRES_USER: baget
      POSTGRES_PASSWORD: password
      POSTGRES_DB: baget
    volumes:
      - postgres_data:/var/lib/postgresql/data

  baget:
    image: loicsharma/baget:latest
    container_name: baget-server
    environment:
      - "BaGet__Storage__Type=FileSystem"
      - "BaGet__Storage__Path=/var/baget/packages"
      - "BaGet__Database__Type=PostgreSql"
      - "BaGet__Database__ConnectionString=Host=postgres;Database=baget;Username=baget;Password=password"
    ports:
      - "5000:80"
    volumes:
      - ./data:/var/baget
    depends_on:
      - baget-postgres
    restart: always
    
volumes:
  postgres_data:
